# Generated by Django 6.0.5 on 2026-05-29 09:24

import django.db.models.deletion
from django.db import migrations, models

import apps.musicians.models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="musicianprofile",
            name="genres",
            field=models.ManyToManyField(blank=True, related_name="profiles", to="musicians.genre"),
        ),
        migrations.CreateModel(
            name="MusicianInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musician_instruments",
                        to="musicians.instrument",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musician_instruments",
                        to="musicians.musicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument__name"],
            },
        ),
        migrations.AddField(
            model_name="musicianprofile",
            name="instruments",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                through="musicians.MusicianInstrument",
                to="musicians.instrument",
            ),
        ),
        migrations.AddConstraint(
            model_name="musicianinstrument",
            constraint=models.UniqueConstraint(
                fields=("profile", "instrument"), name="unique_musician_instrument"
            ),
        ),
    ]
