# Generated by Django 6.0.5 on 2026-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0002_genre_instrument_musicianprofile_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicianprofile",
            name="sound_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
