# Generated by Django 6.0.5 on 2026-06-02 10:06
#
# EDITED after the fact, when search moved to OpenSearch and pgvector was
# removed from the project. This migration used to import `pgvector.django` for
# VectorExtension, VectorField and HnswIndex — and Django imports every
# migration module on every `migrate`, so a historical import keeps a dependency
# alive forever, long after the last row that needed it is gone.
#
# The table this creates is dropped again by search/0003. On an existing
# database that already applied this migration, nothing here runs and the edit
# is invisible. On a fresh database the table is now created with a placeholder
# column instead of a `vector(1536)` one, and then dropped — the same end state,
# reached without the extension.

import django.db.models.deletion
from django.db import migrations, models

import apps.musicians.models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0003_musicianprofile_sound_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                # Was pgvector.django.vector.VectorField(dimensions=1536).
                ("embedding", models.TextField()),
                ("embedding_text", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="musicians.musicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                # Was a pgvector HnswIndex on `embedding`.
            },
        ),
    ]
