# Generated by Django 6.0.5 on 2026-06-02 10:06

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

import apps.musicians.models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0003_musicianprofile_sound_url"),
    ]

    operations = [
        # Must run before any VectorField / HnswIndex is created (CLAUDE.md).
        # Enables the `vector` extension; the RDS master user can run this in prod.
        VectorExtension(),
        migrations.CreateModel(
            name="ProfileEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("embedding_text", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="musicians.musicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="profile_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
