# Generated by Django 6.0.5 on 2026-06-05 13:06

import django.db.models.deletion
from django.db import migrations, models

import apps.musicians.models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0004_profileembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityBlurb",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.musicians.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blurb", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_blurbs_as_a",
                        to="musicians.musicianprofile",
                    ),
                ),
                (
                    "profile_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_blurbs_as_b",
                        to="musicians.musicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile_a", "profile_b"), name="unique_compatibility_pair"
                    )
                ],
            },
        ),
    ]
