# Generated by Django 6.0.5 on 2026-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0005_compatibilityblurb"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicianprofile",
            name="is_open_to_session_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musicianprofile",
            name="session_rate",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
