# Generated by Django 6.0.5 on 2026-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0006_musicianprofile_is_open_to_session_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicianprofile",
            name="rating_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="musicianprofile",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
