# Generated by Django 6.0.5 on 2026-08-19 10:34

from django.db import migrations


class Migration(migrations.Migration):
    # Ordering is load-bearing: search/0002 copies the rows out of this table,
    # so the copy must be applied before the table is dropped. Without this
    # dependency the two are unordered and a deploy can silently destroy every
    # embedding — vectors that cost real OpenAI calls to produce.
    dependencies = [
        ("search", "0002_copy_embeddings_from_musicians"),
        ("musicians", "0007_musicianprofile_rating_avg_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profileembedding",
            name="profile_embedding_hnsw",
        ),
        migrations.DeleteModel(
            name="ProfileEmbedding",
        ),
    ]
