# Generated by Django 6.0.5 on 2026-08-19 10:32

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

import apps.search.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # MUST be first, and must live in THIS app rather than being inherited
        # from musicians/0004. A VectorField cannot be created before the
        # extension exists, and migration order across apps follows the
        # dependency graph — nothing guaranteed musicians ran first, so a fresh
        # database failed with: type "vector" does not exist.
        #
        # Owning it here is also the correct end state: when search gets its own
        # database, that database needs its own extension.
        # CREATE EXTENSION is a no-op when it already exists.
        VectorExtension(),
        migrations.CreateModel(
            name="ProfileEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.search.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_id", models.UUIDField(db_index=True, unique=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("embedding_text", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="search_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
