# Generated by Django 6.0.5 on 2026-08-19 10:32
#
# EDITED after the fact, when this app moved to OpenSearch and pgvector was
# removed. This used to open with `VectorExtension()` and create a
# `vector(1536)` column under an HNSW index. Django imports every migration
# module on every `migrate`, so those imports would have kept pgvector a
# dependency of the project forever — for a table that search/0003 drops.
#
# The `_new_uuid` default is inlined for the same reason: apps/search/models.py
# no longer defines one, because this app no longer has models.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_id", models.UUIDField(db_index=True, unique=True)),
                # Was pgvector.django.vector.VectorField(dimensions=1536).
                ("embedding", models.TextField()),
                ("embedding_text", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-generated_at"],
                # Was a pgvector HnswIndex on `embedding`.
            },
        ),
    ]
