# Generated by Django 6.0.5 on 2026-06-08 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.reviews.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.reviews.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "context_type",
                    models.CharField(choices=[("engagement", "Engagement")], max_length=32),
                ),
                ("context_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "-created_at"], name="reviews_rev_subject_d9ad8f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "context_id"), name="unique_review_per_author_per_context"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_rating_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("author", models.F("subject")), _negated=True),
                        name="review_no_self",
                    ),
                ],
            },
        ),
    ]
