# Generated by Django 6.0.5 on 2026-06-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.social.models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.social.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("posted_listing", "Posted a listing"),
                            ("created_band", "Created a band"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("target_slug", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.social.models._new_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_entries",
                        to="social.activity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["actor", "-created_at"], name="social_acti_actor_i_0b1e34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["owner", "-created_at"], name="social_feed_owner_i_e06f18_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                fields=("owner", "activity"), name="unique_feed_entry"
            ),
        ),
    ]
